#!/bin/bash

n="
ABCORS.netkan
AdvancedFlyByWire.netkan
AdvancedFlyByWire-Linux.netkan
AdvancedFlyByWire-OSX.netkan
AGExt.netkan
AutomatedScreenshots.netkan
BetterScienceLabsContinued.netkan
CameraFocusChanger.netkan
ChampagneBottleRedux.netkan
ClickThroughBlocker.netkan
ContractConfigurator-GrandTours.netkan
ContractConfigurator-KerbinSpaceStation.netkan
ContractConfigurator-RoverMissionsRedux.netkan
ContractConfigurator-UnmannedContracts.netkan
ContractFilterContinued.netkan
CraftImport.netkan
DiazosLandingHeight.netkan
DTV2.netkan
EditorExtensionsRedux.netkan
EngineIgnitorReignited.netkan
EvaFollower.netkan
EVAHandrailsPackContinued.netkan
FilterExtensions.netkan
FilterExtensionsDefaultConfig.netkan
FTLDriveContinued.netkan
InlineBallutes.netkan
JSIPartUtilities.netkan
Kartographer.netkan
KerbalGPSRevived.netkan
KerbalNRAP.netkan
Kerbonov.netkan
KRASH.netkan
KSP-AVC.netkan
KSPLogger.netkan
KWRocketry-CommunityFixes.netkan
KWRocketry-CommunityFixes-interstage.netkan
MagiCore.netkan
MemGraph.netkan
NavHudRenewed.netkan
NEBULADecalsContinued.netkan
NodeHelper.netkan
NovaPunchRebalanced.netkan
NovaPunchRebalanced-Freyja.netkan
NovaPunchRebalanced-Odin.netkan
NovaPunchRebalanced-Thor.netkan
PatchManager.netkan
PersistentDynamicPodNames.netkan
PicoPort4AllSizes.netkan
PreciseNode.netkan
RCSBuildAidCont.netkan
RCSLandAid.netkan
RetractableLiftingSurface.netkan
SelectableDataTransmitter.netkan
ShowFPS.netkan
SpacetuxSA.netkan
StationKeeping.netkan
StructuralTubing.netkan
TankLockRedux.netkan
ThroughTheEyesOfaKerbal.netkan
Toolbar.netkan
TotalTime.netkan
TWR1.netkan
WasdEditorCameraContinued.netkan
YongeTechTreesPlugin-Revived.netkan
ZeroMiniAVC.netkan
ZPIF-4-Stock.netkan"

for i in $n; do
	grep -q vref $i
	rc=$?
	[ $rc -ne 0 ] && echo $i
done
