name: Inflate a chosen module
on:
    workflow_dispatch:
        inputs:
            identifier:
                description: Identifier of module to inflate
                required: true
jobs:
    Inflate_module:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Manual inflate
              uses: ./.github/actions/manual_inflate
              with:
                  AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID     }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_DEFAULT_REGION:    ${{ secrets.AWS_DEFAULT_REGION    }}
                  identifier:            ${{ github.event.inputs.identifier }}
